[package]
name = "qip-wasm-validate-core-2"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
wasmparser = { path = "../../../third_party/rust/wasmparser-0.252.0", default-features = false, features = ["validate", "features", "prefer-btree-collections", "simd"] }

[patch.crates-io]
bitflags = { path = "../../../third_party/rust/bitflags-2.13.0" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
strip = true
