#!/usr/bin/env python3
"""Generate the offline IANA named-service and port finder from pinned CSV."""

import csv
import hashlib
from pathlib import Path
import re
import sys

SOURCE_URL = "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv"
SOURCE_SHA256 = "34328ed0940d889207de6da29bf0e6e1438d604483c8e1ffb03dceab8f7ec26f"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/iana-service-port-data.zig"
UPDATED = "2026-09-11"


def zig_string(value):
    value = " ".join(value.split())
    if any(ord(char) < 32 for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def readable_reference(value):
    def replace(match):
        identifier = match.group(1)
        if identifier.upper().startswith("RFC") and identifier[3:].isdigit():
            return "RFC " + identifier[3:]
        return identifier.strip("_").replace("_", " ")

    return re.sub(r"\[([A-Za-z][A-Za-z0-9_-]*)\]", replace, value)


def main(source):
    payload = Path(source).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected service-port CSV SHA-256: {digest}")
    rows = list(csv.DictReader(payload.decode("utf-8-sig").splitlines()))
    entries = []
    for row in rows:
        name, port, protocol = (row[key].strip() for key in ("Service Name", "Port Number", "Transport Protocol"))
        if not (name and port and protocol):
            continue
        if not re.fullmatch(r"\d+(?:-\d+)?", port) or protocol not in ("tcp", "udp", "sctp", "dccp"):
            raise ValueError(f"invalid named port: {name}, {port}, {protocol}")
        notes = "; ".join(filter(None, (row["Assignment Notes"].strip(), row["Unauthorized Use Reported"].strip())))
        entries.append((name, port, protocol, row["Description"], readable_reference(row["Reference"]), readable_reference(row["Assignee"]), row["Registration Date"], row["Modification Date"], notes))
    protocol_order = {"tcp": 0, "udp": 1, "sctp": 2, "dccp": 3}
    entries.sort(key=lambda row: (int(row[1].split("-", 1)[0]), protocol_order[row[2]], row[0]))
    if len(entries) != 11723 or len({entry[:3] for entry in entries}) != len(entries):
        raise ValueError(f"unexpected or duplicate named ports: {len(entries)}")
    fields = ("name", "port", "protocol", "description", "reference", "assignee", "registered", "modified", "notes")
    output = [
        "// Generated by tools/generate-iana-service-port-tui-data.py. Do not edit by hand.",
        f"// Source: {SOURCE_URL}",
        f"// SHA-256: {SOURCE_SHA256}",
        f"// IANA registry last updated {UPDATED}; only rows with name, port, and protocol are included.",
        f"pub const updated = {zig_string(UPDATED)};",
        "pub const Service = struct {",
    ]
    output.extend(f"    {field}: []const u8," for field in fields)
    output.extend(("};", "", "pub const services = [_]Service{"))
    for values in entries:
        output.append("    .{ " + ", ".join(f".{key} = {zig_string(value)}" for key, value in zip(fields, values)) + " },")
    output.extend(("};", ""))
    OUTPUT.write_text("\n".join(output))
    print(f"wrote {len(entries)} named service/port rows to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} service-names-port-numbers.csv")
    main(sys.argv[1])
