#!/usr/bin/env python3
"""Generate the offline emoji finder from pinned Unicode Emoji 18.0 data.

Download SOURCE_URL, verify its SHA-256, and pass the file to this script.
Only component and fully-qualified rows are emitted. The latter are the RGI
sequences defined by the source; the TUI never invents ZWJ combinations.
"""

import hashlib
from pathlib import Path
import re
import sys

SOURCE_URL = "https://www.unicode.org/Public/18.0.0/emoji/emoji-test.txt"
SOURCE_SHA256 = "8f3735cda1f92a779d78af67cf86066bb1f07143dc22f2ac29394d9bc57ab21a"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/emoji-data.zig"
VERSION = "18.0"
IGNORED_PARTS = {0x200D, 0xFE0E, 0xFE0F}
ROW = re.compile(r"([0-9A-F ]+)\s*;\s*(component|fully-qualified|minimally-qualified|unqualified)\s*#\s*\S+\s+E([0-9.]+)\s+(.+)")


def zig_string(value):
    if any(ord(char) < 32 for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(source):
    payload = Path(source).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected emoji-test SHA-256: {digest}")
    lines = payload.decode("utf-8").splitlines()
    if f"# Version: {VERSION}" not in lines[:15]:
        raise ValueError("unexpected Unicode Emoji version")
    group = subgroup = ""
    entries = []
    for line in lines:
        if line.startswith("# group: "):
            group = line.split(": ", 1)[1]
        elif line.startswith("# subgroup: "):
            subgroup = line.split(": ", 1)[1]
        elif line and not line.startswith("#"):
            match = ROW.fullmatch(line.strip())
            if not match:
                raise ValueError(f"unrecognized emoji row: {line}")
            codepoints, status, version, name = match.groups()
            if status not in ("component", "fully-qualified"):
                continue
            scalars = tuple(int(part, 16) for part in codepoints.split())
            glyph = "".join(chr(scalar) for scalar in scalars)
            if not group or not subgroup or not name:
                raise ValueError(f"missing emoji metadata: {line}")
            entries.append((glyph, name, group, subgroup, version, codepoints.strip(), scalars, status == "component"))
    if len(entries) != 3972 or sum(entry[7] for entry in entries) != 9:
        raise ValueError(f"unexpected emoji count: {len(entries)}")
    if len({entry[6] for entry in entries}) != len(entries):
        raise ValueError("duplicate fully qualified emoji sequence")
    scalar_names = {}
    for _, name, _, _, _, _, scalars, _ in entries:
        significant = [scalar for scalar in scalars if scalar not in IGNORED_PARTS]
        if len(significant) == 1:
            scalar_names.setdefault(significant[0], name)
    output = [
        "// Generated by tools/generate-emoji-tui-data.py. Do not edit by hand.",
        f"// Source: {SOURCE_URL}",
        f"// SHA-256: {SOURCE_SHA256}",
        "// Copyright © 2026 Unicode, Inc. Unicode License v3: tui/lib/UNICODE-LICENSE.txt.",
        f"pub const version = {zig_string(VERSION)};",
        "pub const Emoji = struct {",
        "    glyph: []const u8,",
        "    name: []const u8,",
        "    group: []const u8,",
        "    subgroup: []const u8,",
        "    introduced: []const u8,",
        "    codepoints: []const u8,",
        "    parts: []const u8,",
        "    scalars: []const u32,",
        "    component: bool,",
        "};",
        "",
        "pub const emojis = [_]Emoji{",
    ]
    for glyph, name, group, subgroup, version, codepoints, scalars, component in entries:
        part_names = []
        for scalar in scalars:
            if scalar in IGNORED_PARTS:
                continue
            part_name = scalar_names.get(scalar)
            if part_name and part_name not in part_names:
                part_names.append(part_name)
        fields = (
            f".glyph = {zig_string(glyph)}",
            f".name = {zig_string(name)}",
            f".group = {zig_string(group)}",
            f".subgroup = {zig_string(subgroup)}",
            f".introduced = {zig_string(version)}",
            f".codepoints = {zig_string(codepoints)}",
            f".parts = {zig_string(' '.join(part_names))}",
            ".scalars = &.{ " + ", ".join(f"0x{scalar:X}" for scalar in scalars) + " }",
            f".component = {'true' if component else 'false'}",
        )
        output.append("    .{ " + ", ".join(fields) + " },")
    output.extend(("};", ""))
    OUTPUT.write_text("\n".join(output))
    print(f"wrote {len(entries)} emoji entries to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} emoji-test.txt")
    main(sys.argv[1])
