#!/usr/bin/env python3
"""Generate the offline TLD finder table from pinned IANA downloads.

Download both URLs below and pass the files in that order. The source hashes
guard against silently mixing snapshots or changing the generated data.
"""

import hashlib
from html.parser import HTMLParser
from pathlib import Path
import re
import sys

LIST_URL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
LIST_SHA256 = "85f0cbceb417c98cabb9e3fe357f7752aa799d2b0b36fa915037a331a73ea04f"
DB_URL = "https://www.iana.org/domains/root/db"
DB_SHA256 = "835106f739cbacf15ee9c72696778213c145645799b85b9f2b1750d76774a532"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/tld-data.zig"


class RootDatabase(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_table = False
        self.in_body = False
        self.row = None
        self.cell = None
        self.domain = None
        self.rows = {}

    def handle_starttag(self, tag, attributes):
        attributes = dict(attributes)
        if tag == "table" and attributes.get("id") == "tld-table":
            self.in_table = True
        elif self.in_table and tag == "tbody":
            self.in_body = True
        elif self.in_body and tag == "tr":
            self.row = []
            self.domain = None
        elif self.row is not None and tag == "td":
            self.cell = []
        elif self.cell is not None and tag == "a":
            match = re.fullmatch(r"/domains/root/db/([a-z0-9-]+)\.html", attributes.get("href", ""))
            if match:
                self.domain = match.group(1).upper()

    def handle_data(self, value):
        if self.cell is not None:
            self.cell.append(value)

    def handle_endtag(self, tag):
        if tag == "td" and self.cell is not None:
            self.row.append("".join(self.cell).strip())
            self.cell = None
        elif tag == "tr" and self.row is not None:
            if self.domain is None or len(self.row) != 3 or self.domain in self.rows:
                raise ValueError(f"invalid or duplicate root database row: {self.domain!r}")
            self.rows[self.domain] = tuple(self.row)
            self.row = None
        elif tag == "tbody" and self.in_body:
            self.in_body = False
        elif tag == "table" and self.in_table:
            self.in_table = False


def checked_bytes(path, expected_hash):
    payload = Path(path).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != expected_hash:
        raise ValueError(f"unexpected SHA-256 for {path}: {digest}")
    return payload


def zig_string(value):
    if any(ord(char) < 32 for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(list_path, db_path):
    lines = checked_bytes(list_path, LIST_SHA256).decode("ascii").splitlines()
    version = re.fullmatch(r"# Version (\d+), Last Updated (.+)", lines[0])
    if not version:
        raise ValueError("missing IANA list version")
    domains = [line for line in lines[1:] if line]
    if len(domains) != len(set(domains)) or any(not re.fullmatch(r"[A-Z0-9-]+", name) for name in domains):
        raise ValueError("invalid or duplicate TLD in delegated list")
    database = RootDatabase()
    database.feed(checked_bytes(db_path, DB_SHA256).decode("utf-8"))
    if not set(domains) <= database.rows.keys():
        raise ValueError(f"missing delegated TLDs in root database: {set(domains) - database.rows.keys()}")
    types = {"generic", "country-code", "sponsored", "generic-restricted", "infrastructure"}
    entries = []
    for domain in domains:
        display, kind, manager = database.rows[domain]
        # IANA wraps some right-to-left labels in directional marks. The TUI
        # stores the actual label and avoids embedding display controls.
        display = display.strip("\u200e\u200f")
        manager = " ".join(manager.split())
        if kind not in types or not display.startswith(".") or not manager or manager == "Not assigned":
            raise ValueError(f"invalid metadata for {domain}: {database.rows[domain]}")
        entries.append(("." + domain.lower(), display, kind, manager))
    output = [
        "// Generated by tools/generate-tld-tui-data.py. Do not edit by hand.",
        f"// Delegated list: {LIST_URL}",
        f"// List SHA-256: {LIST_SHA256}",
        f"// Root database: {DB_URL}",
        f"// Database SHA-256: {DB_SHA256}",
        f"// IANA list version: {version.group(1)}; updated {version.group(2)}",
        "pub const snapshot = " + zig_string(version.group(1)) + ";",
        "pub const Tld = struct {",
        "    ascii: []const u8,",
        "    display: []const u8,",
        "    kind: []const u8,",
        "    manager: []const u8,",
        "};",
        "",
        "pub const tlds = [_]Tld{",
    ]
    for entry in entries:
        output.append("    .{ " + ", ".join(f".{field} = {zig_string(value)}" for field, value in zip(("ascii", "display", "kind", "manager"), entry)) + " },")
    output.extend(("};", ""))
    OUTPUT.write_text("\n".join(output))
    print(f"wrote {len(entries)} delegated TLDs to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {sys.argv[0]} tlds-alpha-by-domain.txt root-db.html")
    main(*sys.argv[1:])
