#!/usr/bin/env python3
"""Generate the offline IANA media-type finder from a pinned registry XML file."""

import hashlib
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

SOURCE_URL = "https://www.iana.org/assignments/media-types/media-types.xml"
SOURCE_SHA256 = "edbcb6b4d4a4ef754dafa33fea71dbaf553e8aa887694490546782e93bec0c41"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/iana-media-type-data.zig"
NS = {"i": "http://www.iana.org/assignments"}


def zig_string(value):
    value = " ".join(value.split())
    if any(ord(char) < 32 for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def reference(xref):
    value = xref.get("data", "")
    if xref.get("type") == "rfc":
        return "RFC " + re.sub(r"^rfc", "", value, flags=re.I)
    if xref.get("type") == "person":
        return value.strip("_").replace("_", " ")
    return value


def main(source):
    payload = Path(source).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected media-type XML SHA-256: {digest}")
    root = ET.fromstring(payload)
    updated = root.findtext("i:updated", namespaces=NS)
    if updated != "2026-09-22":
        raise ValueError(f"unexpected registry update date: {updated}")
    entries = []
    for registry in root.findall("i:registry", NS):
        category = registry.get("id")
        for record in registry.findall("i:record", NS):
            file = record.find("i:file", NS)
            media_type = (file.get("name") or file.text) if file is not None else None
            label = record.findtext("i:name", namespaces=NS)
            if not media_type or not media_type.startswith(category + "/") or not label:
                raise ValueError(f"invalid media-type record: {category}, {label}, {media_type}")
            subtype = media_type.split("/", 1)[1]
            qualifier = label[len(subtype):].strip() if label.startswith(subtype) else label
            refs = ", ".join(filter(None, (reference(x) for x in record.findall("i:xref", NS))))
            date = record.get("updated") or record.get("date") or ""
            entries.append((media_type, qualifier, refs, date))
    entries.sort(key=lambda row: row[0].casefold())
    if len(entries) != 2361 or len({entry[0].casefold() for entry in entries}) != len(entries):
        raise ValueError(f"unexpected or duplicate media types: {len(entries)}")
    output = [
        "// Generated by tools/generate-iana-media-type-tui-data.py. Do not edit by hand.",
        f"// Source: {SOURCE_URL}",
        f"// SHA-256: {SOURCE_SHA256}",
        f"pub const updated = {zig_string(updated)};",
        "pub const MediaType = struct {",
        "    name: []const u8,",
        "    qualifier: []const u8,",
        "    references: []const u8,",
        "    date: []const u8,",
        "};",
        "",
        "pub const media_types = [_]MediaType{",
    ]
    for values in entries:
        output.append("    .{ " + ", ".join(f".{key} = {zig_string(value)}" for key, value in zip(("name", "qualifier", "references", "date"), values)) + " },")
    output.extend(("};", ""))
    OUTPUT.write_text("\n".join(output))
    print(f"wrote {len(entries)} media types to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} media-types.xml")
    main(sys.argv[1])
