#!/usr/bin/env python3
"""Generate the country finder's pinned, offline Zig data table.

Download the CSV at SOURCE_URL, verify its SHA-256, then run this script with
the downloaded file as its argument. The output is committed with the component.
"""

import csv
import hashlib
from pathlib import Path
import re
import sys
import unicodedata

SOURCE_COMMIT = "6a595f1a6f10b3d00175fe67375da88f64f7f76b"
SOURCE_URL = (
    "https://raw.githubusercontent.com/datasets/country-codes/"
    f"{SOURCE_COMMIT}/data/country-codes.csv"
)
SOURCE_SHA256 = "67b009b529330b0a6043551189f43faa785c9c3cc0011ad2bdb4eac876356c43"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/country-data.zig"


def zig_string(value):
    if any(ord(char) < 32 for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ascii_name(value):
    value = value.replace("’", "'")
    return unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")


def dial_prefixes(value):
    # The source marks two dialing entries with footnote letters.
    value = re.sub(r" [a-z]$", "", value.strip())
    return ", ".join("+" + part.strip() for part in value.split(",") if part.strip())


def main(source):
    payload = Path(source).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected country data SHA-256: {digest}")
    rows = list(csv.DictReader(payload.decode("utf-8-sig").splitlines()))
    if len(rows) != 249:
        raise ValueError(f"expected 249 country rows, got {len(rows)}")
    countries = []
    for row in rows:
        code = row["ISO3166-1-Alpha-2"].strip()
        name = row["CLDR display name"].strip()
        # The source chooses the CLDR "alt-short" labels US and UK. This
        # directory needs the full familiar names in its country column.
        name = {"US": "United States", "GB": "United Kingdom"}.get(code, name)
        # The source leaves Türkiye's currency blank. CLDR lists TRY as current.
        currencies = {"TR": "TRY"}.get(code, row["ISO4217-currency_alphabetic_code"].strip())
        if not re.fullmatch(r"[A-Z]{2}", code) or not name:
            raise ValueError(f"invalid country: {code!r}, {name!r}")
        countries.append((
            code,
            name,
            ascii_name(name) + (" UK" if code == "GB" else ""),
            row["ISO3166-1-Alpha-3"].strip(),
            currencies,
            dial_prefixes(row["Dial"]),
            row["Capital"].strip(),
            row["Region Name"].strip(),
            row["TLD"].strip(),
        ))
    countries.sort(key=lambda row: (row[2].casefold(), row[0]))
    if len({row[0] for row in countries}) != len(countries):
        raise ValueError("duplicate ISO alpha-2 code")
    fields = ("code", "name", "search_name", "alpha3", "currencies", "dial", "capital", "region", "tld")
    lines = [
        "// Generated by tools/generate-country-tui-data.py. Do not edit by hand.",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {SOURCE_SHA256}",
        "// Source dataset: datasets/country-codes, Public Domain Dedication and License.",
        "// Overrides: familiar US/UK names and TRY for Türkiye (CLDR territory-currency data).",
        "// Dial values are calling prefixes; some include area prefixes after the country code.",
        "pub const Country = struct {",
    ]
    lines.extend(f"    {field}: []const u8," for field in fields)
    lines.extend(("};", "", "pub const countries = [_]Country{"))
    for row in countries:
        lines.append("    .{ " + ", ".join(f".{field} = {zig_string(value)}" for field, value in zip(fields, row)) + " },")
    lines.extend(("};", ""))
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {len(countries)} countries to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} country-codes.csv")
    main(sys.argv[1])
