#!/usr/bin/env python3
"""Generate a pinned offline Can I Use feature table from a caniuse-db tarball."""

import hashlib
from html import unescape
import json
from pathlib import Path
import re
import sys
import tarfile
from datetime import datetime, timezone

VERSION = "1.0.30001812"
SOURCE_URL = f"https://registry.npmjs.org/caniuse-db/-/caniuse-db-{VERSION}.tgz"
SOURCE_SHA256 = "f3e05638e7963c8e0a2e616a8c7ad3ed5cdedd83e5e419c8a56cddad12c049e0"
OUTPUT = Path(__file__).resolve().parents[1] / "tui/lib/caniuse-data.zig"
BROWSERS = ("chrome", "firefox", "safari", "edge")
STATUS = {"y": "Full", "a": "Partial", "n": "No", "p": "No (polyfill available)", "u": "Unknown"}


def plain(value):
    value = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"<[^>]*>", " ", value)
    return " ".join(unescape(value).replace("`", "").split())


def zig_string(value):
    if any(ord(char) < 32 and char != "\n" for char in value):
        raise ValueError(f"control character in {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def status_text(value):
    parts = value.split()
    label = "Disabled by default" if "d" in parts else STATUS[parts[0]]
    extras = []
    if "x" in parts:
        extras.append("prefix required")
    extras.extend(part for part in parts[1:] if part.startswith("#"))
    return label + (" (" + ", ".join(extras) + ")" if extras else "")


def browser_history(feature, agent, browser):
    stats = feature["stats"][browser]
    current = agent["current_version"]
    versions = []
    for item in agent["version_list"]:
        version = item["version"]
        if version in stats:
            versions.append((version, stats[version]))
        if version == current:
            break
    if not versions or versions[-1][0] != current:
        raise ValueError(f"missing current version for {browser}")
    spans = []
    start, last, state = versions[0][0], versions[0][0], versions[0][1]
    for version, value in versions[1:]:
        if value != state:
            spans.append(f"{start}" + (f"–{last}" if last != start else "") + f": {status_text(state)}")
            start, state = version, value
        last = version
    spans.append(f"{start}" + (f"–{last}" if last != start else "") + f": {status_text(state)}")
    note_ids = sorted({int(part[1:]) for _, value in versions for part in value.split()[1:] if part.startswith("#")})
    notes = [f"#{number}: {plain(feature['notes_by_num'][str(number)])}" for number in note_ids]
    return f"Version history: {'; '.join(spans)}." + ("\n" + "\n".join(notes) if notes else "")


def main(source):
    payload = Path(source).read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected caniuse-db SHA-256: {digest}")
    with tarfile.open(source, "r:gz") as archive:
        data = json.load(archive.extractfile("package/fulldata-json/data-2.0.json"))
    features = data["data"]
    if len(features) != 554:
        raise ValueError(f"unexpected feature count: {len(features)}")
    date = datetime.fromtimestamp(data["updated"], timezone.utc).date().isoformat()
    output = [
        "// Generated by tools/generate-caniuse-tui-data.py. Do not edit by hand.",
        f"// Source: {SOURCE_URL}",
        f"// SHA-256: {SOURCE_SHA256}",
        "// License: CC-BY-4.0. Data from caniuse.com.",
        f"// Dataset updated: {date}",
        f"pub const snapshot = {zig_string(date)};",
        "pub const Feature = struct {",
        "    slug: []const u8,",
        "    title: []const u8,",
        "    search: []const u8,",
        "    description: []const u8,",
        "    notes: []const u8,",
        "    summary: [4][]const u8,",
        "    details: [4][]const u8,",
        "};",
        "",
        "pub const features = [_]Feature{",
    ]
    for slug, feature in sorted(features.items(), key=lambda entry: entry[1]["title"].lower()):
        summary = []
        details = []
        for browser in BROWSERS:
            agent = data["agents"][browser]
            version = agent["current_version"]
            summary.append(f"{version} {status_text(feature['stats'][browser][version])}")
            details.append(browser_history(feature, agent, browser))
        search = " ".join((feature["title"], slug, feature.get("keywords", "")))
        fields = {
            "slug": slug,
            "title": plain(feature["title"]),
            "search": plain(search),
            "description": plain(feature["description"]),
            "notes": plain(feature["notes"]),
        }
        output.append("    .{ " + ", ".join(f".{key} = {zig_string(value)}" for key, value in fields.items()) +
                      ", .summary = .{ " + ", ".join(map(zig_string, summary)) + " }, .details = .{ " +
                      ", ".join(map(zig_string, details)) + " } },")
    output.extend(("};", ""))
    OUTPUT.write_text("\n".join(output))
    print(f"wrote {len(features)} features to {OUTPUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} caniuse-db-{VERSION}.tgz")
    main(sys.argv[1])
